swagger: "2.0"
openapi: 3.0.0

info:
  version: 0.1.0
  title: AsstBot API
  description: API description of AsstBot

schemes:
  - https
host: www.xiaodamp.cn/asstbot
basePath: /api

paths:
  /chatbot/survey:
    post:
      summary: Send message to survey chatbot
      description: User send a message to survey chatbot and get the reply
      parameters:
      - in: "body"
        name: "body"
        description: "message to send"
        required: true
        schema:
          oneOf:
          - $ref : "#/FromMsgComponents/LoginMsg"
          - $ref : "#/FromMsgComponents/DialogStartMsg"
          discriminator:
            propertyName: type
            mapping:
              login: "#/FromMsgComponents/LoginMsg"
              dialog-start: "#/FromMsgComponents/DialogStartMsg"       
      responses:
        200:
          description: The message to frontend
          schema:
            $ref: "#/definitions/AsstBotMsg"

#START 新增定义####################################################################
definitions:
  AsstBotMsg:
    type: object     

FromMsgComponents:
  Basemsg:
    type: object
    required:
    - from
    - type
    properties:
      from:
        type: object
        required:
        - id
        properties:
          id: string
      type:
        type: string
        enum:
          - login
          - dialog-start
          - text
          - speech
          - radio-reply
          - checkbox-reply
          - image
          - audio
          - vedio
          - date          
  LoginMsg:
    allOf:
    - $ref: "#/FromMsgComponents/Basemsg"
    - type: object
      required:
      - data
      properties:
        data: object
        properties:
          code: string
  DialogStartMsg:
    allOf:
    - $ref: "#/FromMsgComponents/Basemsg"
    - type: object
      required:
      - data
      properties:
        data: object
        properties:
          scene: 
            type: string
            enum: [test, publish]
          surveyId: string
